source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'STAControlsTests' do
  pod 'KIF', :configurations => ['Debug']
  pod 'KIF/IdentifierTests', :configurations => ['Debug']
end
